### ISSUE TITLE
Issue with PyFFTW

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#198] opened 2015-01-19 12:40 UTC
Hi,

Yesterday I installed PyFFTW and it appears to work smoothly. But when trackpy uses scipy.ndimage.fourier_gaussian on the result of `fftn`, it fails with `datatype not understood`. While the datatype is the same as the numpy function `fftn`

This code reproduces my error:

    import numpy as np
    import trackpy as tp
    
    a = np.random.randint(0, 256, (50,50))
    
    afftw = tp.preprocessing.fftn(a)
    anp = np.fft.fftn(a)
    
    print type(afftw), afftw.dtype, afftw.shape
    print type(anp), anp.dtype, anp.shape  # equal to afftw
    
    tp.preprocessing.fourier_gaussian(anp, (1., 1.))  # no exception
    tp.preprocessing.fourier_gaussian(afftw, (1., 1.))  # exception

The stack:

    C:\Anaconda\lib\site-packages\scipy\ndimage\fourier.pyc in fourier_gaussian(input, sigma, n, axis, output)
        121         sigmas = sigmas.copy()
        122 
    --> 123     _nd_image.fourier_filter(input, sigmas, n, axis, output, 0)
        124     return return_value
        125 
    
    RuntimeError: data type not supported

**Comment by danielballan** [comment] 2015-01-19 21:49
I haven't seen that one before. I ran your code but I cannot reproduce the error. Which versions of pyfftw, numpy, and scipy? See #199, which I've been meaning to write for awhile, so save yourself a minute or two of trouble.

**Comment by caspervdw** [comment] 2015-01-22 09:08
My versions: (u'six', '1.8.0'), (u'numpy', '1.9.0'), (u'scipy', '0.14.0'), (u'matplotlib', u'1.4.0'), (u'pandas', '0.14.1'), (u'scikit-image', None), (u'pyyaml', None), (u'pytables', None), (u'numba', '0.14.0'), (u'pyfftw', '0.10.0'), (u'python', u'2.7.8')

I'll do some updating, maybe this solves the problem.

**Comment by caspervdw** [comment] 2015-01-22 10:58
Updating scipy to 0.15.1 had some effect: now it just hangs on `_nd_image.fourier_filter` instead of giving an error. The numpy-generated FFT just works.
A downgrade to pyfftw 0.9.2 did not make a difference.

**Comment by danielballan** [comment] 2015-01-22 14:29
Hmm. I won't have time to follow up for a few days. I would start by
inspecting attributes of the numpy array at various stages in the
process...before and after _maybe_align() and before and after the fft.

**Comment by caspervdw** [comment] 2015-01-22 16:33
With help of my colleague, I found a difference. `anp.strides = (16L, 800L)` and `afftw.strides = (800L, 16L)`
Transposing or `asfortranarray` or `ascontiguousarray` doesn't help. My working solution is:

    afftw2 = np.empty_like(a, dtype=np.complex128)
    afftw2[:,:] = afftw

This issue could be OS or even C compiler dependent. It may be a good idea to include this in the PyFFTW wrapper in `preprocessing.py`.

**Comment by caspervdw** [comment] 2015-02-02 16:57
What shall I do with this one? Copying the PyFFTW produced result to a new array does cost some performance, but I think that if I have the issue other people may have it as well.

**Comment by tacaswell** [comment] 2015-02-02 17:22
I was going to suggest using `np.array(afftw, dtype=np.complex128)` for efficiency, but decided to bench mark it before sticking my neck out.  Good thing too:

```python
src = np.random.rand(2000, 2500)

def test1():
    a = np.array(src, dtype=np.complex128)

def test2():
    a = np.empty_like(src)
    a[:, :] = src

```

and 

```python
In [20]: %timeit test1()
10 loops, best of 3: 29.7 ms per loop

In [21]: %timeit test2()
100 loops, best of 3: 17.9 ms per loop

```

**Comment by tacaswell** [comment] 2015-02-02 17:24
But, coming back to your question, I would just put the copy in as taking a performance hit is better than not working.

Have you raised this with either the pyfftw or fftw devs?

**Comment by caspervdw** [comment] 2015-02-12 16:08
I checked out PyFFTW 10.0 from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyfftw and the issue is solved! I suggest that we just remove the fix as soon as 0.10.0 is released on pypi.

**Comment by danielballan** [comment] 2015-02-12 16:18
Agreed. As PyFFTW is optional anyway, we can require the latest version.
I'm glad to have this in for now though. Keep an eye and let us know if
0.10.0 releases before 0.3.

**Comment by caspervdw** [comment] 2015-02-17 09:03
Please ignore my previous message, I tested again today and it does not work with 0.10.0. Probably I made a mistake in testing previously. I will tell the pyfftw devs that the problem persists in 0.10.0

**Comment by caspervdw** [comment] 2015-02-17 13:55
I got some news: apparently PyFFTW produces a numpy array of type `clongfloat` (`'G'`), on which fourier_transform crashes:

    a = np.random.randint(0, 256, (50,50))
    fourier_gaussian(a.astype('D'), (1., 1.))  # OK
    fourier_gaussian(a.astype('G'), (1., 1.))  # hangs

**Comment by danielballan** [comment] 2015-08-16 19:41
Closing, now the FFTW is relegated to legacy.

**Closed by danielballan** 2015-08-16 19:41 UTC
