### ISSUE TITLE
compute drift error on a new installation 

### ISSUE THREAD

**Issue by manuescobedo** [soft-matter/trackpy#446] opened 2017-07-14 07:41 UTC
After a new installation of anaconda on a fresh windows and Debian, got the following error while following the tutorial.
I've got installed:  pandas                    0.20.1              np112py27_0  ->    in Windows.
and:                       pandas                    0.20.1              np112py27_0  ->   in Debian
```
d = tp.compute_drift(t1)
plt.figure()
d.plot();
```
```
Traceback (most recent call last):
  File "<ipython-input-17-7119946f263c>", line 1, in <module>

    d = tp.compute_drift(t1)
  File "C:\Users\Alejandro\Anaconda2\lib\site-packages\trackpy\motion.py", line 267, in compute_drift

    delta.reset_index('frame', drop=False, inplace=True)
  File "C:\Users\Alejandro\Anaconda2\lib\site-packages\pandas\core\frame.py", line 3055, in reset_index

    if level is None or i in level:
TypeError: coercing to Unicode: need string or buffer, int found.
```

**Comment by caspervdw** [comment] 2017-07-14 08:18
Tanks for putting the report here on Github! I can reproduce on Py27 with pandas 0.20.1. This seems to be a pandas issue. I can reproduce with pandas 0.20.1 as follows:

```
import pandas as pd
pd.DataFrame({'frame': [0, 1, 2]}).reset_index('frame')
```

**Comment by manuescobedo** [comment] 2017-07-14 08:33
Could you tell me which is the latest stable pandas?

**Comment by apiszcz** [comment] 2017-07-14 10:35
FYI: I'm using/testing numpy 1.13.1 and Pandas 0.20.3 with Python 3.5.3 on
Windows 10/64. No issues detected yet.

**Comment by gfyoung** [comment] 2017-07-14 15:13
> This seems to be a pandas issue.

Hey guys, one of the maintainers (core contributors) from `pandas` here.  We had a discussion @caspervdw re: the potential issue in `pandas` <a href="https://github.com/soft-matter/trackpy/issues/446#issuecomment-315300916">here</a> and came to the conclusion that that was not the case.

Therefore, that would mean the issue would lie on this end.  I suspect that the `t1` object is missing an index for `frame`, which is why the code is breaking.  Reading the documentation, I think that could be made a little clearer IMO.

**Comment by gfyoung** [comment] 2017-07-14 15:49
Update: the issue appears to an old `pandas` version.  If you try upgrading to `0.20.2`, the issue might go away for you @manuescobedo .

**Comment by caspervdw** [comment] 2017-07-15 10:26
I can confirm that the issue disappears on `0.20.2`.

**Comment by caspervdw** [comment] 2017-07-15 21:56
Closing through #447. Thanks @gfyoung for your input and @manuescobedo for the report.

**Closed** 2017-07-15 22:11 UTC
