### ISSUE TITLE
Almost blank walkthrough page

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#426] opened 2017-02-18 00:12 UTC
Clicking the walkthrough link leads to an almost blank page:

http://soft-matter.github.io/trackpy/dev/tutorial/walkthrough.html

**Comment by caspervdw** [comment] 2017-02-18 10:50
Duplicate of #423. I made a PR that solves this issue (#425)

**Closed** 2017-02-18 16:08 UTC
