### ISSUE TITLE
Differences for minmass option in tp.locate()

### ISSUE THREAD

**Issue by ghattab** [soft-matter/trackpy#274] opened 2015-09-01 17:18 UTC
While testing the reproducibility between trackpy v0.2.4 and v0.3.0rc1 on one dataset :
This line under v0.2.4
```python
f0 = tp.locate(frames[0], diameter=11, invert=True, minmass=2000)
```
did correspond to roughly a ```
minmass=8000
``` under v0.3

```
>>>frames[0]
Frame([[  0,   0,   0, ...,   0,   0,   0],
       [  0, 254, 254, ..., 254, 126,   0],
       [  0, 254, 255, ..., 255, 126,   0],
       ..., 
       [  0, 254, 255, ..., 255, 126,   0],
       [  0, 254, 254, ..., 254, 126,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)
```

v0.2.4 and v.0.3.0rc1 output 845 and 887 particles respectively. I confirmed visually the dataset shape with a 3D display of the particle(features) over time.

A scaling factor is mentioned in this [issue](https://github.com/soft-matter/trackpy/issues/247#issuecomment-132254828)

**Comment by caspervdw** [comment] 2015-09-03 07:09
That is strange. The minmass has certainly changed in v0.3, but it should be lower in magnitude in v0.3. Can you provide a single frame from your dataset?

I am working on a minmass_version_change convenience function, I will push this as soon as I tested it.

**Comment by ghattab** [comment] 2015-09-03 12:24
![example_frame.tif](https://cloud.githubusercontent.com/assets/13886161/9658110/0c856ace-5247-11e5-8422-fb9e3208e137.png)

It is indeed strange comparably to what has been mentioned for scaling the minmass. Sending you the original tif file by mail.

**Comment by caspervdw** [comment] 2015-09-05 16:33
Thanks, I will have a look! It could have to do with the image inversion.

**Comment by caspervdw** [comment] 2015-09-06 09:46
I tried to reproduce your results with the image you sent me.

In 0.2.4, I got 40 features with masses ranging from 3500-13000
In 0.3.0rc1, I got 41 features with masses ranging from 3000-11500

So I could not reproduce your issue. There is a convenience function for converting old to new mass in this branch: https://github.com/caspervdw/trackpy/blob/minmass-change/trackpy/feature.py, line 36. Could you check that out?

**Comment by ghattab** [comment] 2015-09-08 13:07
Thanks for verifying it. I confirm, the convenience function works perfectly. And i could not reproduce it either if i just take one frame.
What i meant earlier by the minmass corresponded roughly to a 8000 is assuming that all the other used functions (trackpy.batch, trackpy.link_df and trackpy.filter_stubs) are left untouched between the two versions. So maybe me varying the minimass amounts to palliating for such change, if any. 
In any case, I am now using custom feature detection before using the tracking algorithm, therefore no need for using any minmass or feature diameter.

**Comment by caspervdw** [comment] 2015-09-10 07:05
Good that your issue is solved! Closing

**Closed by caspervdw** 2015-09-10 07:05 UTC
