### ISSUE TITLE
Travis CI tests (Python 3.5, 3.6) failing on reproducibility tests

### ISSUE THREAD

**Issue by charlesreid1** [soft-matter/trackpy#459] opened 2017-11-13 08:29 UTC
Hi there, I'm having some issues getting the Travis tests to pass using a Travis Docker image using the master branch of trackpy.

## Procedure to Reproduce

Pull the latest Travis CI docker image:

```
docker pull travisci/ci-garnet:packer-1510529493-6aa37a4
```

Run the docker image:

```
docker run -it travisci/ci-garnet:packer-1510529493-6aa37a4 /bin/bash
```

Set up the Travis environment:

```
wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; 
chmod +x miniconda.sh
./miniconda.sh -b -p /home/travis/mc
export PATH=/home/travis/mc/bin:$PATH
DEPS="numpy scipy matplotlib pillow pandas!=0.18.0 scikit-image pyyaml pytables numba scikit-learn"
BUILD_DOCS=false
conda update --yes conda
conda config --append channels conda-forge
export TRAVIS_PYTHON_VERSION="3.6"
conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
source activate testenv

git clone https://github.com/soft-matter/trackpy
cd trackpy/
python setup.py install
nosetests --nologcapture -a '!slow'
```

## Failures

This procedure is failing when comparing the output of the `trackpy.batch()` function (loading images from [`video/image_sequence`](https://github.com/soft-matter/trackpy/tree/master/trackpy/tests/video/image_sequence)) with a "known" gold standard in [`reproduce_v0.3.1.csv`](https://github.com/soft-matter/trackpy/blob/master/trackpy/tests/data/reproduce_v0.3.1.csv), inside the `TestReproducibility` class of [`test_reproducibility.py`](https://github.com/soft-matter/trackpy/blob/master/trackpy/tests/test_reproducibility.py#L62). The numbers are just a hair less than the acceptable 95% tolerance (they are within 94.68% tolerance):

```
======================================================================
FAIL: test_characterize (trackpy.tests.test_reproducibility.TestReproducibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trackpy/trackpy/tests/test_reproducibility.py", line 116, in test_characterize
    rtol=self.characterize_rtol)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0

(mismatch 1.2077294685990267%)
 x: array([ 278.235303,  326.533467,  256.92729 ,  245.847123,  335.908993,
        399.643628,  335.056672,  330.889772,  312.991041,  271.132632,
        286.758509,  258.537229,  294.997607,  279.466433,  345.473923,...
 y: array([ 278.235303,  326.533467,  256.92729 ,  244.9001  ,  335.908993,
        399.643628,  335.056672,  330.889772,  312.991041,  271.132632,
        286.758509,  258.537229,  294.997607,  279.466433,  345.473923,...

======================================================================
FAIL: test_find (trackpy.tests.test_reproducibility.TestReproducibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trackpy/trackpy/tests/test_reproducibility.py", line 96, in test_find
    n_lost, len(self.expected)))
AssertionError: 0.9468367889420521 not greater than 0.95 : 100 of 1881 features were not found.

======================================================================
FAIL: test_refine (trackpy.tests.test_reproducibility.TestReproducibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trackpy/trackpy/tests/test_reproducibility.py", line 106, in test_refine
    n_dev, len(self.actual)))
AssertionError: 1367 != 0 : 1367 of 1842 features have moved more than the tolerance.

----------------------------------------------------------------------
Ran 866 tests in 214.823s
```

I am seeing this test failure from the master branch of trackpy, and this is keeping the Travis tests from passing for a completely unrelated change in PR #458.

Can we discuss whether the gold standard should be updated? [This comment](https://github.com/soft-matter/trackpy/blob/master/trackpy/tests/test_reproducibility.py#L87-L91) seems to suggest that the cause is the `gray_dilation` kernel, which was last updated for version 0.3.1. It may perhaps be time to revisit/update the gold standard.

**Comment by charlesreid1** [comment] 2017-11-13 09:27
Note that the remainder of the file produced by the batch command has values that differ by much more than 94.68%. A simple way to produce a "new" version of the gold standard: drop simple_test.py into the `trackpy/tests/ ` directory and run it. This will produce a new gold standard at `trackpy/tests/data/reproduce_0.3.2+178.g82201f7.csv`.

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import six
import os
import numpy as np
import pandas as pd
import pims
from numpy.testing import assert_allclose

import trackpy as tp
from trackpy.preprocessing import invert_image
from trackpy.utils import cKDTree, pandas_iloc

path, _ = os.path.split(os.path.abspath(__file__))

if __name__=="__main__":
    video = pims.ImageSequence(os.path.join(path, 'video', 'image_sequence'))

    print("Compute actual result")
    actual = tp.batch(invert_image(video), diameter=9, minmass=240)
    actual = tp.link_df(actual, search_range=5, memory=2)
    actual.sort_index()
    actual.to_csv( os.path.join(path, 'data',
                            'reproduce_{}.csv'.format(tp.__version__)))

    print("Compute expected result")
    expected = pd.read_csv(os.path.join(path, 'data',
                                        'reproduce_v0.3.1.csv'))
```

There are significant differences in the values beyond the first row. See [this gist](https://gist.github.com/charlesreid1/aae821b00205fc5fd76941878f95763d) for the diff between the two csv files produced.

**Comment by caspervdw** [comment] 2017-11-20 10:52
Thanks @charlesreid1 for the report. As nothing changed in trackpy since the implementation of the reproducibility tests not so long go (#442) my feeling that it is actually related to the imread function (so related to #455).

**Comment by charlesreid1** [comment] 2017-11-20 16:58
I don't think the `imread()` issue is causing this, for two reasons: 
* The raw_mass values for both files are both ~O(6000), whereas if it were related to #455 (continued as soft-matter/pims#280), the mass values would be different by two orders of magnitude.
* There are 37 lines in the 0.3.1 gold standard (at the very end of the file) that are not in the CSV file reproduced with trackpy 0.3.2+178.gf6a105d. That isn't consistent with the imread() issue, which would only change mass values.

I also ruled out soft-matter/pims#282 as a possible issue by building pims from the latest available master branch on Github, rather than letting PyPI take care of it, but that had no effect on the outcome.

Starting from the commit where the reproducibility tests were added, I think it should be possible to reproduce the gold standard, and from there determine what commit (in trackpy or in pims) caused the divergence. I should know more soon.

**Comment by charlesreid1** [comment] 2017-11-20 17:10
Clarification on point 1: raw_mass values are ~O(6000) for both files, and mass values are ~O(300).

**Comment by charlesreid1** [comment] 2017-11-21 08:16
I have a better understanding now of what's causing Travis to fail, so let me report some of my findings.

## Repo Link

First, in the spirit of reproducibility for my reproducibility results, I created a repo with a Dockerfile that makes testing trackpy in an environment identical to Travis trivial and extremely fast (although the container takes about 2 cups of coffee to build): https://github.com/charlesreid1/trackpy-travis-docker/

Using this, I was able to build trackpy at several points in its development (I built it with several tags 0.3.1-0.3.3 and several commits,listed [here](https://github.com/charlesreid1/trackpy-travis-docker/tree/master/shared)) with an Anaconda environment identical to Travis tests, and  reproduced the data contained in the gold standards from each of these.

## Conclusions from tests

My conclusions are written up [in that repository](https://github.com/charlesreid1/trackpy-travis-docker/tree/master/shared) along with all the outputs I used to draw those conclusions, but I'll summarize here:
* Python 2.7 (both up-to-date and legacy test environments) pass the assertion tests and were identical to the gold standards to ~12 decimal places. The gold standards and the standards reproduced by the tags and commits differ by about 70 lines (only the last lines) but have 1,810 matching lines, which means they're really close and thus pass the assertion tests. The results between tags mismatched on those same last 70 lines.
* Python 3.5 results were qualitatively different (values were off by 0.1-1). However, when I sorted the reproduced standards data (and gold standards data) by x and y value, and dumped it out without an index to compare, I found that the x and y values still matched up for many of the rows, but that features were not being tracked across as many frames (so that a feature that had 8 rows in the original gold standard had only 6 in the standard reproduced with Python 3.5).
* The tags don't fail the assertion tests for number of features found, but the individual commits tested *do* fail these assertion tests. The Python 3.5 results between tags and commits largely overlapped (many identical rows), but between the tags and commits tested, there were often missing features (i.e., a feature found by tag 0.3.1 of trackpy would not be found by commit f693a2f3 of trackpy, or vice versa). This meant that the number of features between the tags and commits was similar, but deviated too much for each of the commits.

## Next steps

I still haven't figured out what's causing the O(0.1-1) deviations between Python 2 and Python 3, so I'll look into that and see if it might actually be because of Numpy or Pandas.

## Resolution

The resolution to the failing Travis problem depends on the outcome of the "next steps." Separate versions of the gold standard for Python 2 and Python 3 is kludgey, but would fix the problem as it stands.

I know this is a lot of information and a bit confusing, but have a look at [the conclusions I wrote up](https://github.com/charlesreid1/trackpy-travis-docker/tree/master/shared) and take a look in the `shared/` folder (visualizing the differences using `vim -d` is illuminating). And of course, please ask questions if you have them. I'll follow up when I have findings about the Python 2/Python 3 calculation differences.

**Comment by caspervdw** [comment] 2017-11-21 11:58
Thanks @charlesreid1 for the extensive tests and reports. Clearly, something changed in the last couple of weeks from the succesfull build at https://travis-ci.org/soft-matter/trackpy/builds/282244720 to the current failing build. I do not think this is related to Py2 / Py3 issues as we confirmed before that there is not difference between the two.

So I started going through all trackpy deps that changed version between the old (working) build and the current (failing) one. Turns out that the failing tests appear when I update Scipy from 0.19.1 to 1.0.0. So there must be some API change in scipy that we missed. Judging from the version numbers, there are probably enough API changes to go through.

As the locations of the features change, my guess is that the problem lies in the `refine` (or the `preprocessing` on which refine depends). Track lengths also change (pointing towards `link`), but this is probably due to the different coordinates obtained by `refine`.

So let's start looking at API breakages in:

```
    from scipy.ndimages.filters import uniform_filter1d, correlate1d
    from scipy.ndimage.fourier import fourier_gaussian
```

Or if it's the linking, it must be `scipy.spatial.cKDTree` that is causing trouble.

**Comment by charlesreid1** [comment] 2017-11-21 13:31
Bingo, scipy 0.19 -> 1.0 is the cause (thanks for saving me some time!). When going from python 3 and scipy 0.19 to python 3 and scipy 1.0, the (x,y) coordinate values go from matching the gold standard to 13 decimal places to being off by O(0.1-1). See [the trackpy-travis-docker repo](https://github.com/charlesreid1/trackpy-travis-docker/tree/master/shared_scipy#scipy-019-vs-scipy-10) for explanation and reproduced gold standards from this second round of tests. 

Will have a look at the portions of the scipy API you mentioned and see what I can find out.

**Comment by charlesreid1** [comment] 2017-11-21 14:39
It appears `uniform_filter1d` is our culprit. When it is applied to the image [here](https://github.com/soft-matter/trackpy/blob/5ec1e31093ba52645ff1e1dccdbaceeabcb783ef/trackpy/preprocessing.py#L77-L78), the output is different between scipy 0.19 and scipy 1.0.

To reproduce:

**Machine A: running Scipy 0.19**

```
>>> np.random.seed(1729)
>>> np.sum(uniform_filter1d(np.random.randint(0,255,(1200,1200)),19,0,mode='nearest',cval=0))
126475267
>>> np.mean(uniform_filter1d(np.random.randint(0,255,(1000,1000)),19,0,mode='nearest',cval=0))
126.50800099999999
```

**Machine B: running Scipy 1.0**

```
>>> np.random.seed(1729)
>>> np.sum(uniform_filter1d(np.random.randint(0,255,(1000,1000)),19,0,mode='nearest',cval=0))
126499353
>>> np.mean(uniform_filter1d(np.random.randint(0,255,(1000,1000)),19,0,mode='nearest',cval=0))
126.532032
```

The errors don't look like much, but they accumulate in subsequent steps.

In [scipy's `filters.py`](https://github.com/scipy/scipy/blob/7a37db57132d18881d27812611b67158bc8b6d50/scipy/ndimage/filters.py) the filter is actually implemented in C - specifically, in [scipy's `ni_filters.c`](https://github.com/scipy/scipy/blob/7a37db57132d18881d27812611b67158bc8b6d50/scipy/ndimage/src/ni_filters.c). Checking the history of that file reveals the culprit: roundoff errors in 0.19 that were fixed in [this commit (69977b0bcda8f121e66d3ee21c85424f9b291a92)](https://github.com/scipy/scipy/commit/69977b0bcda8f121e66d3ee21c85424f9b291a92#diff-6615c9e1da61874cfb06840164bd83e0).

**Comment by caspervdw** [comment] 2017-11-21 21:33
OK, so the results obtained using scipy 1.0.0 are actually 'better' than those obtained by scipy 0.19.1. Most probably, this difference in rounding does is no big deal for actual tracking applications (other tests are not failing). The reproducibility tests are just designed to catch these small changes.

I think the best way to go is to make a post-scipy-1.0.0 file and a pre-scipy-1.0.0 file to test against, now that we know what is the cause. Any thoughts? Tagging @nkeim

**Comment by nkeim** [comment] 2017-11-21 21:43
2 files sounds like a good solution. Alternately, we could just make a new file and then skip that test for anything older than scipy v1.0.0. The test would still serve its main purpose.

**Comment by charlesreid1** [comment] 2017-11-22 05:09
I think we should stick with two files as long as scipy versions < 1.0 are supported/tested - and given that scipy 1.0 is just a few weeks old, that could be a while!

**Comment by caspervdw** [comment] 2017-11-24 15:45
I did some more testing and found that the rounding error in Scipy’s uniform filter leads to a decrease of at most 2 in the bandpassed image. Because of the low image contrast this has surprisingly large effect on feature finding and refinement, which is enhanced by the deletion of features that overlap (`separation`). 

We should think carefully about this reproducibility test. The required csv file is about 250kB (my bad), so it has a significant effect on the repo size if we keep updating. Maybe 1 frame is enough for the find, refine and characterize tests? The linking tests could be done on random positions with a fixed seed.

We now have two reproducibility breaks since 0.3.1:

 * The change in grey dilation kernel from round to square (>95% reproducibility)
 * The rounding error change of the uniform filter.

**Comment by charlesreid1** [comment] 2017-11-25 04:29
Thanks for looking into this. I also saw a similar cascading of error from small to large as the filter differences made their way into the feature-finding and dataframe-linking steps.

I noticed that, in the reproducibility test, which loads five frames of video, of the five frames being used to construct the paths, the first 3 and the last 2 are identical:

```
$ pwd
/Users/charles/codes/trackpy/trackpy/tests/video/image_sequence

$ /bin/ls -1 | xargs md5
MD5 (T76S3F00001.png) = b5d001314f5c845e48d4995fe73152af
MD5 (T76S3F00002.png) = b5d001314f5c845e48d4995fe73152af
MD5 (T76S3F00003.png) = b5d001314f5c845e48d4995fe73152af
MD5 (T76S3F00004.png) = f916e0357ff5efa1cd56ad27eb7f0e6d
MD5 (T76S3F00005.png) = f916e0357ff5efa1cd56ad27eb7f0e6d
```

Is that intentional? This might be artificially inflating the overlap between reproducibility tests if the only deviations are between frames 3 and 4, and are diluted with overlap between 1, 2, 3 and 4, 5 (knocking reproducibility down a few percentage points). (This may also help address the size issue.)

I think the check to make sure trackpy is finding the correct number of features in the correct place (static image test), and a check to make sure it is tracking those features in the right way (moving image test), should happen separately. The fact that there are several things breaking the reproducibility test indicates that that one test might be doing too much. If you look at the setup of the `TestReproducibility` class in `test_reproducibility.py`, the process of extracting an image sequence, batching them to find features, and linking the dataframes are all done in one go, and intermediate results are not saved. If we save and test each step individually, that might improve the test.

The `batch()` (or, `locate()`) function is also tested in `test_feature()`, and ideally this suite of test would have failed as well. But those tests are based on generating artificial spots at specified locations, adding noise, and comparing the detected spot locations (the gold standard is mathematically verifiable), whereas the test that failed was based on comparing to an "arbitrary" standard (which was only verifiable with a prior version of the software using an erroneous filter implementation), so I don't think those tests can be improved.

**Comment by caspervdw** [comment] 2017-12-02 15:02
I decided to 1) first break the API some more for v0.4 and 2) make feature-finding a bit more modular before having a look at the reproducibility tests. The API breakages make sense to do before changing the 'golden standard', and the modular feature finding will make more modular reproducibility testing possible.

Please have a look at the recent PRs #465 and #466 .

**Comment by caspervdw** [comment] 2018-01-23 12:14
Closing through #471

**Closed by caspervdw** 2018-01-23 12:14 UTC
