### ISSUE TITLE
Conda conflict vs. Python 3.4

### ISSUE THREAD

**Issue by pablocobelli** [soft-matter/trackpy#253] opened 2015-07-23 01:59 UTC
Congratulations on a great python package. 
However, trying to install it in anaconda with python 3.4 gives:

Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|###################################################| 100%

Hint: the following packages conflict with each other:
  - trackpy
  - python 3.4*

So I was wondering if you plan on making it available for Python 3.4 or if this incompatibility is something inherent to the package that could not be fixed without major recoding.

**Comment by nkeim** [comment] 2015-07-23 02:09
This sounds like a conda packaging issue on our part. As far as we know trackpy is fully compatible with Python 3.4; in fact, our automated CI testing runs on Python 3.4 (installed via miniconda).

In the meantime, `pip install trackpy` should install the same stable version as `conda install trackpy`. Let us know if it doesn't work!

**Comment by pablocobelli** [comment] 2015-07-23 11:40
@nkeim: Thanks for the quick answer. I'm able to confirm that pip install trackpy successfully installs pims-0.2.2, tifffile-0.6.2, and trackpy-0.2.4.

**Comment by danielballan** [comment] 2015-07-26 19:19
Yep, the issue is related to numba, and it will be resolved in the upcoming release.

**Comment by pablocobelli** [comment] 2015-07-26 21:25
@danielalban: That's great! Thanks for your quick response. Congrats again for a very useful package.

**Comment by danielballan** [comment] 2015-08-16 21:42
The master branch conda recipe is compatible with 3.4. I just ran a build which you can try out if you like.

```
conda install -c danielballan trackpy==v0.2.3-278 python==3.4
```

(Note: Unfortunately, due to some buggled tagging in the 0.2.4 release, the version reads as 0.2.3+ even though it is actually more up-to-date than 0.2.4.)

**Comment by danielballan** [comment] 2015-08-24 23:13
@pablocobelli We have a release candidate for v0.3.1 with Python 3.4 conda packages. See #266 for installation instructions. Please reopen this issue if you find it does not work for you.

**Closed by danielballan** 2015-08-24 23:13 UTC
