### ISSUE TITLE
Link_df runs very slow with large data sets

### ISSUE THREAD

**Issue by mdgratale** [soft-matter/trackpy#294] opened 2015-10-12 15:03 UTC
I'm attempting to link particle positions to form trajectories using link_df for a data set containing ~1,700 particles for 90,000 frames.  In attempting this, I noticed link_df was running very slow.  After 12 hours, the code had completed under 8,000 frames (I estimate that the entire data set would have taken maybe 4 days).  While I understand that that is a huge data set, I previously was able to complete the linking of the same number of particles (~1,700) for 24,000 frames, which took about 4 hours.  Naively, I was expecting the time to scale linearly, and so this 90k frame data set would take 12-16 hours (much more reasonable than 4 days).  But this was not the case.

My hypothesis is there is a memory issue.  The 90k frame data file is ~3 GB, and uses 10-15% of my machine's memory (linux server, found using "top" command).  Any suggestions on how this process can be sped up?

Some useful information, versions of various packages are: python 2.7.10, numba 0.12.2, numpy 1.8.2, trackpy 0.2.4rc7, and pandas 0.14.1.

Thanks for your help.

**Comment by tacaswell** [comment] 2015-10-12 15:16
See http://soft-matter.github.io/trackpy/generated/trackpy.link_df_iter.html#trackpy.link_df_iter and http://soft-matter.github.io/trackpy/tutorial.html#processing-large-data-sets  for an out-of-core linking.

You shouldn't really be seeing issues with memory unless you are forcing paging to disk.

My knee-jerk guess is that the images are denser in one case than the other.

My second slightly more considered reaction is that in `link_df` the base dataframe gets updated on every iteration, which depends on the size of the data frame, so you are probably going to get `O(N**2)` scaling in the number of frames.

You can also drop down to the base functions and skip pandas altogether

http://soft-matter.github.io/trackpy/api.html#low-level-linking-api

**Comment by caspervdw** [comment] 2015-10-12 15:36
It could also be related to #280. Performance is greatly reduced if you pass a view to a DataFrame, instead of a DataFrame. Checking the difference can be tricky.

Does the problem persist if you explicitly copy the dataframe before linking? Something like

    f = f.copy()

**Comment by mdgratale** [comment] 2015-10-12 15:51
Thanks for the fast replies!  I have not tried making a copy.  I was also going to look into using link_df_iter.  I will try those to start and report back.  Thanks again!

**Comment by mdgratale** [comment] 2015-10-13 18:18
Copying the dataframe before linking did not help.  Next up on my list is link_df_iter.

**Comment by nkeim** [comment] 2015-10-13 19:50
That's too bad. See also #256, which is fixed in the development version.

**Comment by mdgratale** [comment] 2015-10-14 14:21
A quick update.  Overnight I ran link_df with a 1,000 frame data set and a 10,000 frame data set using %timeit.  The 1k data set took just under 3 minutes (168 seconds to be exact), while the 10k data set took over 2 hours (8557 seconds to be exact).  So as the number of frames increase, the time it takes to do the linking from frame to frame noticeably increases.  Both the 1k and 10k sets came from my original 90k frame data set. This is a dense colloid packing, so the number of particles in each frame fluctuates, but only by a couple of particles in each frame.

**Comment by tacaswell** [comment] 2015-10-14 14:55
Can you do the same thing with `%prun` ?

**Comment by mdgratale** [comment] 2015-10-14 18:26
Ran with %prun.

**Comment by mdgratale** [comment] 2015-10-14 18:34
OK so I've been trying to attach the results from the %prun for both the 10k and 1k frame cases, but Github is not enjoying this.  So I have to copy and paste in a very ugly way the first few lines, which show there is definitely a difference when the number of frames increases.  There are changes across the board but 'get_indexer' and a pandas process are the processes that change the most.
For 10k frames:
1151769500 function calls (1151689497 primitive calls) in 8354.203 seconds

   Ordered by: internal time
  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  20001 2470.651    0.124 2470.651    0.124 {method 'get_indexer' of 'pandas.index.IndexEngine' objects}
 35491556  868.766    0.000  868.993    0.000 {numpy.core.multiarray.array}
    10000  863.047    0.086  863.047    0.086 {pandas.algos.take_1d_int64_float64}
    40001  735.181    0.018  738.721    0.018 common.py:202(_isnull_ndarraylike)
    20000  667.655    0.033  667.667    0.033 ops.py:524(na_op)
    10002  426.604    0.043  426.604    0.043 {gc.collect}
    20001  420.847    0.021  453.022    0.023 numeric.py:2373(array_equal)
    60010  227.025    0.004 1101.368    0.018 common.py:620(take_nd)
        1  161.115  161.115 8354.200 8354.200 linking.py:396(link_df)
    20004  145.912    0.007  145.912    0.007 {numpy.core.multiarray.putmask}
    30000   96.807    0.003 4122.750    0.137 generic.py:1594(reindex)
    10000   94.653    0.009 1092.084    0.109 internals.py:532(putmask)
 17532057   94.484    0.000  471.054    0.000 series.py:134(__init__)
    10001   90.932    0.009  957.885    0.096 linking.py:633(link_iter)

And for 1k frames:
ncalls  tottime  percall  cumtime  percall filename:lineno(function) 
     1002   41.968    0.042   41.968    0.042 {gc.collect}
     2001   20.773    0.010   20.773    0.010 {method 'get_indexer' of 'pandas.index.IndexEngine' objects}
     1001   10.047    0.010  100.566    0.100 linking.py:633(link_iter)
  1753361    9.919    0.000   49.170    0.000 series.py:134(__init__)
  3549464    8.053    0.000    8.072    0.000 {numpy.core.multiarray.array}
     1000    6.084    0.006    6.084    0.006 {pandas.algos.take_1d_int64_float64}
  1751358    5.763    0.000   11.425    0.000 series.py:2397(_sanitize_array)
 22964847    5.505    0.000    5.548    0.000 {isinstance}
     4001    5.420    0.001    5.702    0.001 common.py:202(_isnull_ndarraylike)
      999    4.777    0.005    8.760    0.009 linking.py:890(assign_candidates)
  1754361    4.438    0.000   17.528    0.000 internals.py:3035(__init__)
     2000    4.282    0.002    4.283    0.002 ops.py:524(na_op)
  1758366    3.689    0.000   11.551    0.000 internals.py:1804(make_block)
  1744356    3.646    0.000   51.474    0.000 frame.py:512(iterrows)
     1000    3.630    0.004   72.365    0.072 linking.py:613(_build_level)
  1758366    3.498    0.000    7.108    0.000 internals.py:59(__init__)
  1743356    3.458    0.000   16.451    0.000 linking.py:615(<lambda>)
        1    3.369    3.369  202.215  202.215 linking.py:396(link_df)

Again, sorry this is in an ugly format.  Github did not like the files I had.

**Comment by mdgratale** [comment] 2015-10-14 18:36
Wow, sorry did not preview that before posting, that is AWFUL!  Will try to get everything in a better format.

**Comment by tacaswell** [comment] 2015-10-14 18:50
@mdgratale Abused my gh privileges and edited your comments.  The trick is triple back ticks ('`')

**Comment by tacaswell** [comment] 2015-10-14 18:53
Also interesting that in the 1k case `gc.collect` is the most expensive operation !?!

**Comment by nkeim** [comment] 2015-10-14 19:08
Fascinating! I will ponder this.

The `gc.collect()` thing reminds me of #280, although @mdgratale seems to have ruled it out. But it does seem to fit with the story of pandas running amok. (Bad day at the zoo?)

@mdgratale , when you get the chance, you may want to use [Gist](https://gist.github.com) to share the full tracebacks.

**Comment by mdgratale** [comment] 2015-10-14 19:25
Ah there we go.  Thank you!  How obvious it it that I am a Python and Github beginner?  Don't know if this matters much but the data was "pretracked" (i.e. features/particles found in each frame) in a different environment, loaded into python as a numpy array, and then turned into a DataFrame before being input into link_df.  

Good point @nkeim.  Sorry, I forgot, while running this for the subset of frames from the entire movie, I did not make a copy but rather just the view, i.e. the exact same situation as in #280.  Just reran after making copies of 1k and 10k data.  `gc.collect()` is now not the most expensive operation.  However, 1k data was completed while 10k data was on frame ~400 (and I actually started 10k data a minute or two before 1k).  Gist for 1k results here: https://gist.github.com/mdgratale/2354a0b00cf5b0d69e03

**Comment by tacaswell** [comment] 2015-10-14 20:44
Nope, a major design feature of trackpy is that the locating and the tracking are completely decoupled.

**Comment by caspervdw** [comment] 2015-10-14 21:03
You might try to update pandas and tackpy to rule out recent bugfixes?

**Comment by tacaswell** [comment] 2015-10-14 21:10
Compare 

```
  2001   20.773    0.010   20.773    0.010 {method 'get_indexer' of 'pandas.index.IndexEngine' objects}
  20001 2470.651    0.124 2470.651    0.124 {method 'get_indexer' of 'pandas.index.IndexEngine' objects}
```

and 

```
     1001   10.047    0.010  100.566    0.100 linking.py:633(link_iter)
    10001   90.932    0.009  957.885    0.096 linking.py:633(link_iter)
```

The time to link frame-to-frame is about constant and the total time scale linearly with the number of frames (both of which are as expected).  The time to shove stuff into the dataframe per-frame also scales about linearly with the size of the data frame (as expected) and the number of times you do that also scales linearly with the number of frames (as expected) giving N^2 scaling using `link_df`.

I would be very suprised if there where any bug fixes what would change that scaling.

**Comment by nkeim** [comment] 2015-10-14 21:31
Nicely put.

`link_df()` does not assume that the data are in chronological order. It is a side effect of using Pandas that the most general way to do it is also the easiest to code, and that for most users it happens fast enough that they never notice.

I'm now seriously thinking that `link_df_iter()` is going to fix this for @mdgratale . `groupby` is super efficient and runs only once. If you use `pandas.concat(..., ignore_index=True).reset_index(inplace=True, drop=True)` to handle the output, you'll get a big array in memory in a fraction of the time.

The "bug fix" for `link_df()` would be to (optionally) assume that the DataFrame was sorted by frame number, and then use lower-level methods to read and write. That would keep everything to a constant time per frame. Or just make `link_df()` a wrapper around `link_df_iter()`, and get rid of the ability to link a DataFrame in-place.

**Comment by mdgratale** [comment] 2015-10-14 21:38
OK so first off:  Thank you all for your help with this.  It is greatly appreciated.  I will be sure to try `link_df_iter()` next.  Also, here is the 10k frame data `%prun` gist: https://gist.github.com/mdgratale/de5551a739f764fee659

Again, thank you thank you thank you.

**Comment by caspervdw** [comment] 2015-10-15 17:28
Agree on the analysis and updating would probably not change much.

@nkeim Another way for the bug fix of `link_df` could be collecting the particle labels and indices in a pre-initialized numpy array and converting to a Series object afterwards.

**Comment by mdgratale** [comment] 2015-10-23 14:33
Update:  `link_df_iter` works fantastically!  It linked all 90k frames in about 4 hours.  One thng to note though, `link_df_iter` was able to do 10k frames in ~15 minutes, where as `link_df ` does 10k frames in a little over 2 hours.  It appears for most data sets of significant number of frames and/or particles `link_df_iter` works lightning fast compared to `link_df`.  My problem has been solved.  I can leave it up to you all about closing this issue, as I am not sure if you'd rather keep it open if you plan on making any changes to `link_df` based off of this.  Thanks again for all of your help.

**Comment by nkeim** [comment] 2015-10-23 15:34
Hooray!! Yes, I'd like to keep this issue open. Performance that unexpectedly scales as *N*^2, without at least a warning for users, is a bug. Thank you, @mdgratale , for the detective work and for hearing out our ideas!

**Question for everyone:** does anyone value in-place linking? (i.e., when `link_df()` adds a `particle` column to an existing DataFrame, instead of making a new DataFrame that includes `particle`.) We have a lot of code devoted to it and it seems to perennially be causing bugs and surprises. The easiest fix (by far) to the problem identified by @mdgratale would be to keep `link_df()` but have it always make a copy.

In principle, in-place *should* be more memory-efficient, but this matters only when your data size is between ~50% and ~100% of available memory, your features come to you in a monolithic file format, and you need your linked tracks to all be in memory at the end. This sounds exactly like @mdgratale if he had 500,000 frames. Is that a likely possibility?

**Comment by caspervdw** [comment] 2015-10-26 22:02
Making a copy by default is ok for me, but I don't see how making a copy would solve this issue. The problem is the repeated calls to `df.update`,  right? Please correct me if I'm wrong

**Comment by nkeim** [comment] 2015-10-26 23:35
Yes, the problem is not in-place linking per se, but the way `link_df()` was written to enable in-place linking. You are right that we could use a method other than `df.update`, perhaps by going through `iloc` instead. 

But here's the motivation for my crazy idea: `link_df()` has repeatedly brought out the worst in Pandas, and repairing it is only going to make it longer and hairier. But compare the [source code of `link_df()`](https://github.com/soft-matter/trackpy/blob/master/trackpy/linking.py#L472) with the [source code of `NullPredict.link_df()`](https://github.com/soft-matter/trackpy/blob/master/trackpy/predict.py#L56). As best I can tell, the *only* functional difference is `copy_features=False`.

**Comment by caspervdw** [comment] 2015-10-27 12:19
Wow that one is certainly much neater. I am :+1: for dropping inplace functionality and getting this much cleaner code.

Another approach would be to have `_link_df_iter` yield *labels* (as a plain iterable), which `link_df` collects into a pre-initialized `ndarray` object. Adding this (inplace or not) to the dataframe should be easy as `df['particle'] = labels`, and this is very efficient.

**Comment by danielballan** [comment] 2015-10-29 14:26
>  this matters only when your data size is between ~50% and ~100% of available memory...

Yeah, this was the scenario I found myself in in grad school, before our HDF5/streaming stuff was ready to use. I agree we can drop in-place now.

**Closed** 2017-02-18 16:32 UTC
